version: 2

brews:
  - name: ace-dt
    ids: [default]
    commit_author:
      name: goreleaser[bot]
      email: bot@goreleaser.com
    commit_msg_template: |
      fix(ace-dt): updated to {{.Tag}}
    directory: Formula
    homepage: https://github.com/act3-ai/data-tool
    description: "Homebrew Bottle installer with a focus on performance and mobility."
    license: "MIT"
    skip_upload: auto
    test: |
      system "#{bin}/ace-dt --version"
    extra_install: |
      generate_completions_from_executable(bin/"ace-dt", "completion")

      # Generate manpages
      mkdir "man" do
        system bin/"ace-dt", "gendocs", "man", "."
        man1.install Dir["*.1"]
        # man5.install Dir["*.5"]
      end
    repository:
      owner: act3-ai
      name: homebrew-tap
      branch: bump-ace-dt-{{.Tag}}
      git:
        url: git@github.com:act3-ai/homebrew-tap.git
        private_key: "{{.Env.TAP_DEPLOY_KEY}}"
    url_template: "https://github.com/act3-ai/data-tool/releases/download/{{.Tag}}/ace-dt-{{.Tag}}-{{.Runtime.Goos}}-{{.Runtime.Goarch}}"
