version: 2

builds:
  - id: ace-dt
    binary: ace-dt-v{{.Version}}-{{.Os}}-{{.Arch}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.build={{.Version}}
    env:
      - CGO_ENABLED=0
      - GOFIPS140=latest
    main: ./cmd/ace-dt/

archives:
  - id: ace-dt-archives
    ids:
      - ace-dt
    format: "tar.gz"
    builds_info:
      mode: 755

release:
  github:
    owner: act3-ai
    name: data-tool
  ids:
    - ace-dt
  make_latest: envOrDefault "RELEASE_LATEST" "true"
  mode: replace # if we need to re-release, don't duplicate the release notes

checksum:
  name_template: "ace-dt_v{{ .Version }}_checksums.txt"
  algorithm: sha256
  ids:
    - ace-dt
  disable: false # be explicit, as docs aren't clear on the default

brews:
  - name: ace-dt
    ids: [ace-dt-archives]
    commit_author:
      name: "{{ .Env.RELEASE_AUTHOR }}"
      email: "{{ .Env.RELEASE_AUTHOR_EMAIL }}"
    commit_msg_template: |
      fix(ace-dt): updated to {{ .Tag }}
    homepage: https://github.com/act3-ai/data-tool
    description: "A CLI tool for packaging, uploading, and downloading data from OCI registries."
    license: "MIT"
    skip_upload: auto # don't upload if prerelease
    test: |
      system "#{bin}/ace-dt version"
    extra_install: |
      generate_completions_from_executable(bin/"ace-dt", "completion")

      # Generate manpages
      mkdir "man" do
        system bin/"ace-dt", "gendocs", "man", "."
        man1.install Dir["*.1"]
      end
    directory: Formula
    repository:
      owner: act3-ai
      name: homebrew-tap
      branch: bump-ace-dt-{{ .Tag }}
      git:
        url: git@github.com:act3-ai/homebrew-tap.git
        private_key: "{{ .Env.GITHUB_TOKEN }}" # set in .envrc.private
      pull_request:
        enabled: true
    url_template: "https://github.com/act3-ai/data-tool/releases/download/{{.Tag}}/ace-dt-{{ .Tag }}-{{ .Runtime.Goos }}-{{ .Runtime.Goarch }}"
