version: 2

builds:
  - id: ace-dt
    binary: ace-dt
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.build={{.Version}}
    env:
      - CGO_ENABLED=0
      - GOFIPS140=latest
    main: ./cmd/ace-dt/

archives:
  - id: ace-dt-archives
    ids:
      - ace-dt
    formats: ["tar.gz"]
    builds_info:
      mode: 755
    name_template: "ace-dt-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - src: releases/v{{ .Version }}.md
        strip_parent: true

release:
  github:
    owner: act3-ai
    name: data-tool
  ids:
    - ace-dt-archives
  make_latest: envOrDefault "RELEASE_LATEST" "false" # don't add 'latest' tag by default
  mode: replace # if there's a need to re-release, don't duplicate the release notes
  skip_upload: false

checksum:
  name_template: ace-dt-v{{ .Version }}-checksums.txt
  algorithm: sha256
  ids:
    - ace-dt-archives
  disable: false

homebrew_casks:
  - name: ace-dt
    directory: Casks
    conflicts:
      - formula: ace-dt
    commit_author:
      name: "{{ .Env.RELEASE_AUTHOR }}"
      email: "{{ .Env.RELEASE_AUTHOR_EMAIL }}"
    commit_msg_template: |
      fix(ace-dt): brew cask update for ace-dt version {{ .Tag }}
    homepage: https://github.com/act3-ai/data-tool
    description: "A CLI tool for packaging, uploading, and downloading data from OCI registries."
    license: "MIT"
    skip_upload: auto # don't upload if prerelease
    repository:
      owner: act3-ai
      name: homebrew-tap
      branch: bump-ace-dt-{{ .Tag }}
      git:
        url: 'ssh://git@github.com:act3-ai/homebrew-tap.git'
        private_key: "{{ .Env.SSH_PRIVATE_KEY }}" # set in .envrc.private
      pull_request:
        enabled: true
    url:
      template: "https://github.com/act3-ai/data-tool/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      using: ":homebrew_curl"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            # replace 'foo' with the actual binary name
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/foo"]
          end
          generate_completions_from_executable(bin/"ace-dt", "completion")
          mkdir "man" do
            system bin/"ace-dt", "gendocs", "man", "."
            man1.install Dir["*.1"]
          end
          system "#{bin}/ace-dt version"
    uninstall:
      delete:
        - "~/.cache/ace/dt/"
