version: 2

builds:
  - id: ace-dt
    binary: ace-dt-{{.Version}}-{{.Os}}-{{.Arch}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.build={{.Version}}
    env:
      - CGO_ENABLED=0
      - GOFIPS140=latest
    main: ./cmd/ace-dt/

archives:
  - format_overrides:
    - formats: [ 'binary' ]

brews:
  - name: ace-dt
    ids: [ace-dt]
    commit_author:
      name: goreleaser[bot]
      email: bot@goreleaser.com
    commit_msg_template: |
      fix(ace-dt): updated to {{.Tag}}
    directory: Formula
    homepage: https://github.com/act3-ai/data-tool
    description: "A CLI tool for packaging, uploading, and downloading data from OCI registries."
    license: "MIT"
    skip_upload: auto
    test: |
      system "#{bin}/ace-dt version"
    extra_install: |
      generate_completions_from_executable(bin/"ace-dt", "completion")

      # Generate manpages
      mkdir "man" do
        system bin/"ace-dt", "gendocs", "man", "."
        man1.install Dir["*.1"]
      end
    repository:
      owner: act3-ai
      name: homebrew-tap
      branch: bump-ace-dt-{{.Tag}}
      git:
        url: git@github.com:act3-ai/homebrew-tap.git
        private_key: "{{.Env.TAP_DEPLOY_KEY}}"
    url_template: "https://github.com/act3-ai/data-tool/releases/download/{{.Tag}}/ace-dt-{{.Tag}}-{{.Runtime.Goos}}-{{.Runtime.Goarch}}"
