builds:
  - id: "ace-dt"
    main: "./cmd/ace-dt"
    env:
      - GOPRIVATE=git.act3-ace.com
    flags:
      - -trimpath
    ldflags:
      - -X main.version={{.Env.VERSION}}
      - -s -w # strip symbols (make the binary smaller)
      - -extldflags "-static"
