# Site information
site_name: Data Tool Docs
site_description: "Documentation Site for ASCE Data Tool"
site_url: https://ace.git.act3-ace.com/data/tool
repo_url: https://git.act3-ace.com/ace/data/tool
repo_name: ACE/Data/Tool
edit_uri_template: https://git.act3-ace.com/ace/data/tool/-/blob/main/{path}

# Theme configuration
theme:
  name: material
  favicon: 
  logo:
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - content.code.copy
    - toc.integrate
    - navigation.path

# list directories or files that should not be built in the site
# exclude_docs: |

# list any pages that should be excluded from the nav
# not_in_nav: |

plugins:
  - search
  # - pdf-export:
      # set combined to `true` to export all site pages into one PDF
      # combined: false
      # media_type: print
      # add CICD env variable `MKDOCS_PDF_EXPORT` and set to `1` to prevent builds during development
      # enabled_if_env: MKDOCS_PDF_EXPORT

markdown_extensions:
  # The mdx_truly_sane_lists extension allows list indentation other than 4 spaces which is typically required for MkDocs sites; manual pipeline config is required to use this
  - mdx_truly_sane_lists
  # Creates links for headings
  - toc:
      permalink: true
  # Code highlighting behavior
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # attr_list enables UI buttons
  - attr_list

############################################################
# Navigation
############################################################
# Conventions:
# Use "↗" to suffix external links in the sidebar
# Use "↳" to prefix internal links in the sidebar
nav:
  - Home: index.md
  - Get Started:
    - Quick Start Guide: get-started/quick-start-guide.md
    - Configuration Guide: get-started/configuration-guide.md
    - Installation Guide: get-started/installation-guide.md
  - User Guide: usage/user-guide.md
  - Concepts:
    - About: usage/concepts/about.md
    - Bottle Creator Guide: usage/concepts/bottle-creator.md
    - Bottle Anatomy Guide: usage/concepts/bottle-anatomy.md
    - Labels and Selectors Guide: usage/concepts/labels-selectors.md
    - Mirror Usage Guide: usage/concepts/mirror.md
  - Tutorials:
    - About: usage/tutorials/about.md
    - Mirror Tutorial: usage/tutorials/mirror.md
    - Bottle Anatomy Tutorial: usage/tutorials/bottle-anatomy.md
  - Support:
    - Get Support: support/about.md
    - FAQ: support/faq.md
  - Contribute:
    - Developer Guide: contribute/developer-guide.md
# Examples of commonly used nav pages are provided below for convenience
  # - "Get Started": quick-start-guide.md
  # - "User Guide": user-guide.md
  # - "Contribute": developer-guide.md
  # - "Support": support.md
